SELECT JNT.IDJTAOPE, JNT.ORDEN,
JNT.CODNAVE,
RZ08.TCMPVP AS NOMNAVE,
RI22.NVJES,
JNT.TIPOPLAN,
JNt.CONTENE,
JNT.OPEPORTU,
JNT.TIPOCONT,
JNT.CLASE,
JNT.TAMANIO,
JNT.REFRIGER,
MAE.FCINPLN,
MAE.HORAINI,
IFNULL(RE07.FFNOPR,0) AS FECFINOPERA,
IFNULL(RE07.HFNOPR,0) AS HORFINOPERA,
IFNULL(RE07.FFNDSC,0) AS FECFINDESCA,
IFNULL(RE07.HFNDSC,0) AS HORFINDESCA,
IFNULL(RE07.FCOFF1,0) AS FECCUTOFF,
IFNULL(RE07.HCOFF1,0) AS HORCUTOFF,
IFNULL(RI24.NGUIIN,0) AS GUIAINGRESO,
IFNULL(RE02.NGSLCN ,0) AS GUIASALIDA,
MAE.ESTADO
FROM "DC@RNSLIB".PPJNTAOPED JNT
INNER JOIN "DC@RNSLIB".PPJNTAOPEM MAE ON JNT.IDJTAOPE = MAE.IDJTAOPE AND MAE.ESTADO = 'A'
LEFT JOIN  "DC@RNSLIB".RZIT22 RI22 ON JNT.ORDEN = RI22.NORSRN
LEFT JOIN "DC@RNSLIB".RZET02 RE02 ON  JNT.ORDEN = RE02.NORSRN AND JNT.CONTENE = CONCAT(RE02.CPRCN4, RE02.NSRCN4)
LEFT JOIN "DC@RNSLIB".RZET08 RE08 ON JNT.ORDEN = RE08.NORSRN
LEFT JOIN "DC@RNSLIB".RZET07 RE07 ON RE08.NMRLQO = RE07.NMRLQO
LEFT JOIN "DC@RNSLIB".RZIT24 RI24 ON JNT.ORDEN = RI24.NORSRN AND JNT.CONTENE = CONCAT(RI24.CPRCN3, RI24.NSRCN3) AND RI24.SESTRG ='A'
LEFT JOIN "DC@RNSLIB".RZZK08 RZ08 ON JNT.CODNAVE = RZ08.CVPRCN 
GROUP BY ORDEN,CODNAVE,JNT.TIPOPLAN,IFNULL(RE07.FFNOPR,0),IFNULL(RE07.FFNDSC,0),IFNULL(RE07.FCOFF1,0),MAE.FCINPLN,JNt.CONTENE,JNT.OPEPORTU,IFNULL(RE02.NGSLCN ,0),
RZ08.TCMPVP,JNT.IDJTAOPE,RI22.NVJES,
RI24.NGUIIN,
JNT.TIPOCONT,
JNT.TAMANIO,MAE.ESTADO,MAE.HORAINI,JNT.CLASE,IFNULL(RE07.HFNOPR,0),IFNULL(RE07.HFNDSC,0),IFNULL(RE07.HCOFF1,0),
JNT.REFRIGER
ORDER BY JNT.CONTENE