
CREATE OR REPLACE PROCEDURE  DC@DESLIB.SP_ACCIONES_PPMODULOS(
	IN  @IDMDLO INTEGER,
    IN  @NMMDLO VARCHAR(50),
    IN  @NMMENU VARCHAR(100),
    IN  @PPVISTA VARCHAR(100),
    IN  @PPCNTRL VARCHAR(100),
	IN  @SESTRG VARCHAR(1),
	IN  @ACCION VARCHAR(1)
)
BEGIN
DECLARE IDMAX INTEGER; 
SET IDMAX = (SELECT IFNULL((MAX(IDMDLO)+1),1) FROM DC@DESLIB.PPMODULO );

IF @ACCION = 'I' 
	THEN 
	INSERT INTO DC@DESLIB.PPMODULO(NMMDLO, SESTRG, IDMDLO, NMMENU, PPVISTA, PPCNTRL) VALUES(@NMMDLO,@SESTRG, IDMAX, @NMMENU, @PPVISTA, @PPCNTRL);
END IF;

IF @ACCION = 'U' 
	THEN 
	UPDATE DC@DESLIB.PPMODULO 
	SET NMMDLO = @NMMDLO, SESTRG = @SESTRG,  NMMENU = @NMMENU,  PPVISTA = @PPVISTA, PPCNTRL = @PPCNTRL
	WHERE IDMDLO = @IDMDLO;
END IF;

IF @ACCION = 'D' 
	THEN 
	UPDATE DC@DESLIB.PPMODULO SET SESTRG = '*' WHERE IDMDLO = @IDMDLO;
END IF;

END ;

