
CREATE OR REPLACE PROCEDURE  DC@DESLIB.SP_ACCIONES_PPACCESOUSUARIO(
	IN  @IDUSER INTEGER,
	IN  @IDMDLO INTEGER,
	IN  @PPINSERT INTEGER,
	IN  @PPUPDATE INTEGER,
	IN  @PPDELETE INTEGER,
	IN  @PPEXPORT INTEGER,
	IN  @PPPRINT INTEGER,
	IN  @SESTRG VARCHAR(1),
	IN  @ACCION VARCHAR(1)
)
BEGIN


IF @ACCION = 'I' 
	THEN 
	INSERT INTO DC@DESLIB.PPACCESOUSUARIO(IDUSER, IDMDLO, PPINSERT, PPUPDATE, PPDELETE, PPEXPORT, PPPRINT, SESTRG) 
 	VALUES(@IDUSER, @IDMDLO, @PPINSERT, @PPUPDATE, @PPDELETE, @PPEXPORT, @PPPRINT, @SESTRG);
END IF;

IF @ACCION = 'U' 
	THEN 
	UPDATE DC@DESLIB.PPACCESOUSUARIO 
	SET PPINSERT = @PPINSERT, PPUPDATE= @PPUPDATE, PPDELETE= @PPDELETE, PPEXPORT= @PPEXPORT,PPPRINT= @PPPRINT WHERE IDUSER = @IDUSER AND IDMDLO = @IDMDLO;
END IF;

IF @ACCION = 'D' 
	THEN 
	UPDATE DC@DESLIB.PPACCESOUSUARIO SET SESTRG = '*'  WHERE IDUSER = @IDUSER AND IDMDLO = @IDMDLO;
END IF;

END ;

