
CREATE PROCEDURE DC@RNSLIB.SP_ACCIONES_PPJNTAOPED ( 
	IN @IDJTAOPE VARCHAR(10), 
	IN @ORDEN NUMERIC(8,0),
	IN @CODNAVE VARCHAR(10),
	IN @CONTENE VARCHAR(7),
	IN @CLASE VARCHAR(3),
	IN @OPEPORTU  VARCHAR(5),
	IN @TAMANIO NUMERIC(3,0),
	IN @PESOMAN NUMERIC(6,2),
	IN @TIPOCONT VARCHAR(3),
	IN @REFRIGER VARCHAR(2),
	IN @FCHFNDSC VARCHAR(10),
	IN @HORFNDSC VARCHAR(10),
	IN @TIPOPLAN VARCHAR(10),
	IN @FCHCUTOFF NUMERIC(8,0),
	IN @HORCUTOFF NUMERIC(6,0),
	IN @FCHCTOFFR NUMERIC(8,0),
	IN @HORCTOFFR NUMERIC(6,0),
	IN @ESTADO VARCHAR(2), 
	IN @ACCION VARCHAR(1) ) 
	LANGUAGE SQL 
	SPECIFIC DC@RNSLIB.SP_ACCIONES_PPJNTAOPED 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
BEGIN 
	
	IF @ACCION = 'I' 
			THEN 
			INSERT INTO "DC@RNSLIB".PPJNTAOPED(IDJTAOPE, ORDEN, CODNAVE, CONTENE, CLASE, TAMANIO, PESOMAN, TIPOCONT, FCHFNDSC, HORFNDSC, TIPOPLAN, FCHCUTOFF, HORCUTOFF, FCHCTOFFR, HORCTOFFR, ESTADO)
		VALUES(@IDJTAOPE, @ORDEN, @CODNAVE, @CONTENE, @CLASE, @TAMANIO, @PESOMAN, @TIPOCONT, @FCHFNDSC, @HORFNDSC, @TIPOPLAN, @FCHCUTOFF, @HORCUTOFF, @FCHCTOFFR, @HORCTOFFR, @ESTADO);
		END IF ; 
		
		IF @ACCION = 'D' 
			THEN 
			UPDATE DC@RNSLIB . PPJNTAOPED SET ESTADO = '*' WHERE IDJTAOPE = @IDJTAOPE ; 
		END IF ; 
END 
