CREATE OR REPLACE PROCEDURE DC@RNSLIB.SP_CONSULTA_PLANIFICACION_CAB ( 
IN @IDJTAOPE VARCHAR(11),
IN @ESTADO VARCHAR(1),
IN @FECHA NUMERIC(8,0),
IN @ACCION VARCHAR(1)
) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DC@RNSLIB.SP_CONSULTA_PLANIFICACION_CAB 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QGPL , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
DECLARE STRSQL VARCHAR ( 5000 ) ; 
DECLARE CU_01 CURSOR WITH RETURN FOR S1 ; 
IF @ACCION = 'T' THEN
SET STRSQL ='SELECT IDJTAOPE, FCINPLN, HORAINI, FCFNPLN, HORAFIN, CNTTUR3, CNTTUR1, CNTTUR2, AUTH1, AUTH2, AUTH3, AUTH4, USERCRE, FECHCRE, HORCRE, USERUPD, FECHUPD, HORUPD, ESTADO
	FROM "DC@RNSLIB".PPJNTAOPEM WHERE ESTADO = TRIM('''|| @ESTADO || ''')';
END IF;

IF @ACCION = 'F' THEN
SET STRSQL ='SELECT IDJTAOPE, FCINPLN, HORAINI, FCFNPLN, HORAFIN, CNTTUR3, CNTTUR1, CNTTUR2, AUTH1, AUTH2, AUTH3, AUTH4, USERCRE, FECHCRE, HORCRE, USERUPD, FECHUPD, HORUPD, ESTADO
	FROM "DC@RNSLIB".PPJNTAOPEM WHERE ESTADO = TRIM('''|| @ESTADO || ''') AND  FCINPLN = ' || @FECHA;
END IF;


PREPARE S1 FROM STRSQL ; 
OPEN CU_01 ; 
  
END  