CREATE OR REPLACE PROCEDURE DC@RNSLIB.SP_CONSULTA_JNTADASHBOARDM ( 
IN @FECHA VARCHAR(8),
IN @ACCION VARCHAR(1)
) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DC@RNSLIB.SP_CONSULTA_JNTADASHBOARDM
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QGPL , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
DECLARE STRSQL VARCHAR ( 5000 ) ; 
DECLARE CU_01 CURSOR WITH RETURN FOR S1 ; 

SET STRSQL ='';

IF(@ACCION='T') THEN
SET STRSQL ='SELECT VW.CODNAVE, VW.NOMNAVE, VW.NVJES, VW.AMNFS, VW.NMNFEN, 
(SELECT IFNULL(SUM(QCNTSL),0) FROM "DC@RNSLIB".RZZT19 r WHERE SESTRG =''A''  AND NORSRN = 
(SELECT NORSRN FROM "DC@RNSLIB".RZIT22 r WHERE r.CVPRCN = VW.CODNAVE AND r.NVJES = VW.NVJES AND r.AMNFS = VW.AMNFS AND r.NMNFEN = VW.NMNFEN AND R.CTPOOP =2 AND SESTRG =''A'' ) ) AS MANEXPO,
(SELECT IFNULL(COUNT(NORSRN),0) FROM "DC@RNSLIB".RZZT18 r WHERE NORSRN =  
(SELECT NORSRN FROM "DC@RNSLIB".RZIT22 r WHERE r.CVPRCN = VW.CODNAVE AND r.NVJES = VW.NVJES AND r.AMNFS = VW.AMNFS AND r.NMNFEN = VW.NMNFEN AND R.CTPOOP =2 AND SESTRG =''A'' ) ) AS ENVIEXPO,
(SELECT COUNT(DISTINCT CONCAT(CPRCN3, NSRCN3) ) FROM "DC@RNSLIB".RZIT24 WHERE  NORSRN = 
(SELECT NORSRN FROM "DC@RNSLIB".RZIT22 r WHERE r.CVPRCN = VW.CODNAVE AND r.NVJES = VW.NVJES AND r.AMNFS = VW.AMNFS AND r.NMNFEN = VW.NMNFEN AND R.CTPOOP =1 AND SESTRG =''A'' ) ) AS MANIMPO,
(SELECT DISTINCT COUNT(DISTINCT CONCAT(CPRCN3, NSRCN3) ) FROM "DC@RNSLIB".RZIT24 WHERE NBLRCR >0 AND NORSRN = 
(SELECT NORSRN FROM "DC@RNSLIB".RZIT22 r WHERE r.CVPRCN = VW.CODNAVE AND r.NVJES = VW.NVJES AND r.AMNFS = VW.AMNFS AND r.NMNFEN = VW.NMNFEN AND R.CTPOOP =1 AND SESTRG =''A'' ) ) AS RECIIMPO,
FECFINOPERA, HORFINOPERA, FECFINDESCA, HORFINDESCA, FECCUTOFF, HORCUTOFF, ESTADO
FROM "DC@RNSLIB".VWJNTAOPEACTIVAS VW WHERE VW.FECFINOPERA =0
GROUP BY VW.CODNAVE, VW.NOMNAVE, VW.NVJES, VW.FECFINOPERA, VW.HORFINOPERA, VW.FECFINDESCA, VW.HORFINDESCA, VW.FECCUTOFF, VW.HORCUTOFF, VW.ESTADO,VW.AMNFS, VW.NMNFEN';
END IF;

IF(@ACCION='F') THEN
SET STRSQL ='SELECT VW.CODNAVE, VW.NOMNAVE, VW.NVJES, VW.AMNFS, VW.NMNFEN, 
(SELECT COUNT(NOMNAVE) FROM "DC@RNSLIB".VWJNTAOPEACTIVAS v WHERE v.NOMNAVE = vw.NOMNAVE AND TIPOPLAN =''E'') AS MANEXPO,
(SELECT COUNT(NOMNAVE) FROM "DC@RNSLIB".VWJNTAOPEACTIVAS v WHERE v.NOMNAVE = vw.NOMNAVE AND TIPOPLAN =''E'' AND v.GUIASALIDA >0) AS ENVIEXPO,
(SELECT COUNT(NOMNAVE) FROM "DC@RNSLIB".VWJNTAOPEACTIVAS v WHERE v.NOMNAVE = vw.NOMNAVE AND TIPOPLAN =''I'') AS MANIMPO,
(SELECT COUNT(NOMNAVE) FROM "DC@RNSLIB".VWJNTAOPEACTIVAS v WHERE v.NOMNAVE = vw.NOMNAVE AND TIPOPLAN =''I'' AND v.GUIAINGRESO >0) AS RECIIMPO,
FECFINOPERA, HORFINOPERA, FECFINDESCA, HORFINDESCA, FECCUTOFF, HORCUTOFF, ESTADO
FROM "DC@RNSLIB".VWJNTAOPEACTIVAS VW
WHERE vw.FECFINOPERA =0  AND VW.FCINPLN = '||@FECHA ||'
GROUP BY VW.CODNAVE, VW.NOMNAVE, VW.NVJES, VW.FECFINOPERA, VW.HORFINOPERA, VW.FECFINDESCA, VW.HORFINDESCA, VW.FECCUTOFF, VW.HORCUTOFF, VW.ESTADO,VW.AMNFS, VW.NMNFEN';
END IF;

PREPARE S1 FROM STRSQL ; 
OPEN CU_01 ; 
  
END  ;