CREATE OR REPLACE PROCEDURE DC@RNSLIB.SP_CONSULTA_DSPLACAS(
IN @PLACA VARCHAR(6),
IN @ACCION VARCHAR(1)
) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DC@RNSLIB.SP_CONSULTA_DSPLACAS 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QGPL , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
BEGIN 
	DECLARE STRSQL VARCHAR ( 5000 ) ; 
DECLARE CU_01 CURSOR WITH RETURN FOR S1 ; 
  
SET STRSQL = '';

	IF @ACCION = 'T'THEN
		SET STRSQL = 'SELECT RZ04.NPLCCM,RZ04.CTRSP,SESTCM, RZ02.TCMPTR FROM "DC@RNSLIB".RZIK04 RZ04
					 LEFT JOIN "DC@RNSLIB".RZIK02 RZ02 ON RZ04.CTRSP = RZ02.CTRSP  WHERE RZ04.SESTRG <> ''*''';
	END IF;
	IF @ACCION = 'U'THEN
			SET STRSQL = 'SELECT TOP 1 RZ04.NPLCCM,RZ04.CTRSP,SESTCM, RZ02.TCMPTR FROM "DC@RNSLIB".RZIK04 RZ04
					 LEFT JOIN "DC@RNSLIB".RZIK02 RZ02 ON RZ04.CTRSP = RZ02.CTRSP  WHERE  RZ04.SESTRG <> ''*'' AND RZ04.NPLCCM = '''||@PLACA||''' ORDER BY RZ04.CTRSP DESC';
		END IF;
	
	PREPARE S1 FROM STRSQL ; 
OPEN CU_01 ;
END  
;