--  Generar SQL 
--  Versión:                   	V7R1M0 100423 
--  Generado en:              	03/02/20 15:18:04 
--  Base de datos relacional:       	IASP 
--  Opción de estándares:          	DB2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","APPDB2" ; 
  
CREATE OR REPLACE PROCEDURE DC@RNSLIB.SP_CONSULTA_PPACCESOUSUARIO ( 
	IN @IDUSER INTEGER , 
	IN @IDMDLO INTEGER , 
	IN @ACCION CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DC@RNSLIB.SP_CONSULTA_PPACCESOUSUARIO 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QGPL , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
DECLARE STRSQL VARCHAR ( 5000 ) ; 
DECLARE CU_01 CURSOR WITH RETURN FOR S1 ; 
SET STRSQL = '' ; 
  
IF @ACCION = 'T' THEN 
	SET STRSQL = 'SELECT ACC.IDUSER, USU.USERNM, ACC.IDMDLO, MODU.NMMDLO, MODU.NMMENU, MODU.PPVISTA, MODU.PPCNTRL, 
CASE ACC.PPINSERT WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPINSERT, 
CASE ACC.PPUPDATE WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPUPDATE, 
CASE ACC.PPDELETE WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPDELETE, 
CASE ACC.PPEXPORT WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPEXPORT, 
CASE ACC.PPPRINT WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPPRINT, 
ACC.SESTRG FROM DC@RNSLIB.PPACCESOUSUARIO ACC
INNER JOIN DC@RNSLIB.PPUSUARIO USU ON ACC.IDUSER = USU.IDUSER AND USU.SESTRG <> ''*''
INNER JOIN DC@RNSLIB.PPMODULO MODU ON ACC.IDMDLO = MODU.IDMDLO AND MODU.SESTRG <> ''*'' 
WHERE ACC.SESTRG <> ''*''' ; 
END IF ; 
  
IF @ACCION = 'U' THEN 
	SET STRSQL = 'SELECT ACC.IDUSER, USU.USERNM, ACC.IDMDLO, MODU.NMMDLO, MODU.NMMENU, MODU.PPVISTA, MODU.PPCNTRL,
CASE ACC.PPINSERT WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPINSERT, 
CASE ACC.PPUPDATE WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPUPDATE, 
CASE ACC.PPDELETE WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPDELETE, 
CASE ACC.PPEXPORT WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPEXPORT, 
CASE ACC.PPPRINT WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPPRINT, 
ACC.SESTRG FROM DC@RNSLIB.PPACCESOUSUARIO ACC
INNER JOIN DC@RNSLIB.PPUSUARIO USU ON ACC.IDUSER = USU.IDUSER AND USU.SESTRG <> ''*''
INNER JOIN DC@RNSLIB.PPMODULO MODU ON ACC.IDMDLO = MODU.IDMDLO AND MODU.SESTRG <> ''*'' 
WHERE ACC.SESTRG <> ''*'' AND ACC.IDUSER = ' || @IDUSER ; 
	 
END IF ; 
  
IF @ACCION = 'M' THEN 
	SET STRSQL = 'SELECT ACC.IDUSER, USU.USERNM, ACC.IDMDLO, MODU.NMMDLO, MODU.NMMENU, MODU.PPVISTA, MODU.PPCNTRL,
CASE ACC.PPINSERT WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPINSERT, 
CASE ACC.PPUPDATE WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPUPDATE, 
CASE ACC.PPDELETE WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPDELETE, 
CASE ACC.PPEXPORT WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPEXPORT, 
CASE ACC.PPPRINT WHEN 1 THEN ''SI'' ELSE ''NO'' END AS PPPRINT, 
ACC.SESTRG FROM DC@RNSLIB.PPACCESOUSUARIO ACC
INNER JOIN DC@RNSLIB.PPUSUARIO USU ON ACC.IDUSER = USU.IDUSER AND USU.SESTRG <> ''*''
INNER JOIN DC@RNSLIB.PPMODULO MODU ON ACC.IDMDLO = MODU.IDMDLO AND MODU.SESTRG <> ''*'' 
WHERE ACC.SESTRG <> ''*'' AND ACC.IDUSER = ' || @IDUSER || ' AND ACC.IDMDLO = ' || @IDMDLO ; 
	 
END IF ; 
  
  
IF @ACCION = 'A' THEN 
SET STRSQL = 'SELECT IDMDLO, NMMDLO, SESTRG
FROM DC@DESLIB.PPMODULO
WHERE SESTRG <> ''*'' AND IDMDLO NOT IN (SELECT IDMDLO FROM "DC@DESLIB".PPACCESOUSUARIO A WHERE  SESTRG <> ''*'' AND A.IDUSER=' || @IDUSER || ')' ; 
END IF ; 
  
PREPARE S1 FROM STRSQL ; 
OPEN CU_01 ; 
  
END  ;
