CREATE OR REPLACE PROCEDURE DC@DESLIB.SP_CONSULTA_OT_DETALLE ( 
IN @FECHA CHAR(8)
) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DC@DESLIB.SP_CONSULTA_OT_DETALLE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QGPL , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
DECLARE STRSQL VARCHAR ( 5000 ) ; 
DECLARE CU_01 CURSOR WITH RETURN FOR S1 ; 
SET STRSQL ='';


	SET STRSQL = 'SELECT R01.CGRONG, R02.NORDTR, R02.CSRVNV, k20.TCMTRF AS SERVICIO, R02.NCRRLT, R02.CCMPN, R02.CDVSN, R02.QSRVC, R02.PSRVC, R02.FPRGOT, R02.HPRGOT, R02.UPRGOT, R02.CPRCN1, R02.NSRCN1, R02.SESTRG
FROM "DC@DESLIB".RZVT02W R02
INNER JOIN "DC@DESLIB".RZVT01 R01 ON R02.NORDTR = R01.NORDTR AND R01.SESTRG <>''*''
INNER JOIN "DC@DESLIB".RZIK20 K20 ON R02.CSRVNV = K20.CSRVNV AND R02.CDVSN = K20.CDVSN AND R02.CCMPN = K20.CCMPN
WHERE R02.FPRGOT = ' || @FECHA ; 

PREPARE S1 FROM STRSQL ; 
OPEN CU_01 ; 
  
END  ;