CREATE OR REPLACE PROCEDURE DC@RNSLIB.SP_CONSULTA_PLANIFICACION_DET ( 
IN @IDJTAOPE VARCHAR(11),
IN @ESTADO VARCHAR(1),
IN @ACCION VARCHAR(1)
) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DC@RNSLIB.SP_CONSULTA_PLANIFICACION_DET 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QGPL , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
DECLARE STRSQL VARCHAR ( 5000 ) ; 
DECLARE CU_01 CURSOR WITH RETURN FOR S1 ; 
IF @ACCION = 'U' THEN
SET STRSQL ='SELECT IDJTAOPE, ORDEN, CODNAVE, RZ08.TCMPVP AS NOMNAVE,  CONTENE, OPEPORTU,  CLASE,TAMANIO, PESOMAN, TIPOCONT, REFRIGER, TIPOPLAN, ESTADO
FROM DC@RNSLIB.PPJNTAOPED JNTA
LEFT JOIN DC@RNSLIB.RZZK08 RZ08 ON JNTA.CODNAVE = RZ08.CVPRCN
WHERE JNTA.IDJTAOPE = TRIM('''|| @IDJTAOPE || ''')';
END IF;

PREPARE S1 FROM STRSQL ; 
OPEN CU_01 ; 
  
END  