CREATE OR REPLACE PROCEDURE DC@RNSLIB.SP_CONSULTA_DSBREVETE(
IN @BREVETE VARCHAR(6),
IN @ACCION VARCHAR(1)
) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DC@RNSLIB.SP_CONSULTA_DSBREVETE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QGPL , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
BEGIN 
	DECLARE STRSQL VARCHAR ( 5000 ) ; 
DECLARE CU_01 CURSOR WITH RETURN FOR S1 ; 
  
SET STRSQL = '';

	IF @ACCION = 'T'THEN
		SET STRSQL = 'SELECT SESTRG, NBRVCH, TNMBCH
FROM IASP."DC@RNSLIB".RZIK03 WHERE (NBRVCH !='' '' OR TNMBCH !='' '') AND SESTRG =''A''';
	END IF;
	IF @ACCION = 'U'THEN
			SET STRSQL = 'SELECT SESTRG, NBRVCH, TNMBCH
FROM IASP."DC@RNSLIB".RZIK03 WHERE (NBRVCH !='' '' OR TNMBCH !='' '') AND SESTRG =''A'' AND NBRVCH = '''||@BREVETE||'''';
		END IF;
	
	PREPARE S1 FROM STRSQL ; 
OPEN CU_01 ;
END  