CREATE OR REPLACE PROCEDURE DC@DESLIB.SP_CONSULTA_ORDENTRABAJO(
IN @IN_TIPO Numeric(1,0),
IN @IN_DOCUMENTO VARCHAR(100)
) 
	 DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DC@DESLIB.SP_CONSULTA_ORDENTRABAJO 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QGPL , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
BEGIN 
	DECLARE STRSQL VARCHAR ( 5000 ) ; 
DECLARE CU_01 CURSOR WITH RETURN FOR S1 ; 
  
SET STRSQL = '';

	IF @IN_TIPO = 1 THEN
		SET STRSQL = 'SELECT RZ22.NORSRN AS RECALADA, RZ22.CVPRCN AS CODNAVE, RK08.TCMPVP AS NAVE, RZ22.NVJES, RZ22.CTPOOP, 
CASE RZ22.CTPOOP WHEN 1 THEN ''IMPORTACION'' ELSE ''EXPORTACION'' END  AS REGIMEN, RZ22.CLNNSS AS LINEA, RZ24.CPRTDC AS CODPTOORI,
RK09.TCMPR1 AS PTOORIGEN, rw31.CCLNTW AS CODCLIE, RM01.TCMPCL AS CLIENTE, RZ24.CAGVLT AS CODAGEN, RZ24.NCRCNE AS ITEM, CONCAT(RZ24.CPRCN3, RZ24.NSRCN3) AS CONTENEDOR,
CONCAT(RZ25.CTPOC2,RZ25.TTMNCN1) AS CLASE, Rk11.TCMAA AS AGENTE, RZ24.CTPCR1 AS TIPO,1 AS CANTSOLIC, rz24.NCNCOR AS BLMASTER, rz22.CPRLLN AS CODPTOLLE, RK09LL.TCMPR1 AS PTOLLEGADA, 
RK11.CCLNT AS FACTURAR, rz24.NCRCNE AS CORRELATIVO
FROM "DC@DESLIB".RZIT24 RZ24
INNER JOIN "DC@DESLIB".rzit22 RZ22 ON RZ24.NORSRN = RZ22.NORSRN
LEFT JOIN "DC@DESLIB".RZZK08 RK08 ON RZ22.CVPRCN = RK08.CVPRCN
LEFT JOIN "DC@DESLIB".RZZK09 RK09 ON RZ24.CPRTDC = RK09.CPRTOR
LEFT JOIN "DC@DESLIB".RZZK09 RK09LL ON RZ22.CPRLLN = RK09LL.CPRTOR
LEFT JOIN "DC@DESLIB".RZZK11 RK11 ON RZ24.CAGVLT = RK11.CAGNAD
LEFT JOIN "DC@DESLIB".RZIW31 RW31 ON RZ24.NCNEM1 = RW31.NCNEM1 AND rz24.NCRCNE = rw31.NCRCNE AND rz24.NORSRN = rw31.NORSRN
LEFT JOIN "DC@DESLIB".RZIT25 RZ25 ON RZ24.NORSRN = RZ25.NORSRN AND rz24.CPRCN3 = rz25.CPRCN4 AND rz24.NSRCN3 = rz25.NSRCN4
LEFT JOIN "DC@DESLIB".RZZM01 RM01 ON rw31.CCLNTW = RM01.CCLNT
WHERE RZ24.NCNEM1 = ''' || @IN_DOCUMENTO ||'''';
	END IF;
	
	PREPARE S1 FROM STRSQL ; 
OPEN CU_01 ;
END  
;