--  Generar SQL 
--  Versión:                   	V7R1M0 100423 
--  Generado en:              	04/11/19 13:14:15 
--  Base de datos relacional:       	IASP 
--  Opción de estándares:          	DB2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","DC@DESLIB" ; 
  
CREATE PROCEDURE DC@DESLIB.SP_REGISTRAR_DETALLE_ORD_TRABAJO ( 
	IN IN_NORDTR NUMERIC(10,0),
	IN IN_CSRVNV NUMERIC(3,0),
	IN IN_NCRRLT NUMERIC(4,0),
	IN IN_CCMPN CHAR(2),
	IN IN_CDVSN CHAR(1),
	IN IN_CRBCTC NUMERIC(3,0),
	IN IN_QSRVC DECIMAL(15,5),
	IN IN_PSRVC DECIMAL(15,5),
	IN IN_ITRFSR DECIMAL(15,5),
	IN IN_CMNDA5 NUMERIC(3,0),
	IN IN_CPRVD CHAR(6),
	IN IN_CCDRLL NUMERIC(5,0),
	IN IN_TOBSRV CHAR(25),
	IN IN_QATNAN DECIMAL(15,5),
	IN IN_PATNAN DECIMAL(15,5),
	IN IN_TOBSR1 CHAR(25),
	IN IN_FLIQSR NUMERIC(8,0),
	IN IN_HLIQSR NUMERIC(6,0),
	IN IN_ULIQSR CHAR(10),
	IN IN_SESTSR CHAR(1),
	IN IN_SESTRG CHAR(1),
	IN IN_TOBSR CHAR(25),
	IN IN_SQNCB CHAR(1),
	IN IN_SESFAC CHAR(1),
	IN IN_SVLRZ CHAR(1),
	IN IN_FINREE NUMERIC(8,0),
	IN IN_HINREE NUMERIC(6,0),
	IN IN_FFIREE NUMERIC(8,0),
	IN IN_HFIREE NUMERIC(6,0),
	IN IN_CZNLLN NUMERIC(3,0)
	) 
	LANGUAGE SQL 
	SPECIFIC DC@DESLIB.SP_REGISTRAR_DETALLE_ORD_TRABAJO 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
  
INSERT INTO IASP."DC@DESLIB".RZVT02(NORDTR, CSRVNV, NCRRLT, CCMPN, CDVSN, CRBCTC, QSRVC, PSRVC, ITRFSR, CMNDA5, CPRVD, CCDRLL, TOBSRV, QATNAN, PATNAN, TOBSR1, FLIQSR, HLIQSR, ULIQSR, SESTSR, SESTRG, TOBSR, SQNCB, SESFAC, SVLRZ, FINREE, HINREE, FFIREE, HFIREE, CZNLLN)
VALUES(IN_NORDTR, IN_CSRVNV, IN_NCRRLT, IN_CCMPN, IN_CDVSN, IN_CRBCTC, IN_QSRVC, IN_PSRVC, IN_ITRFSR, IN_CMNDA5, IN_CPRVD, IN_CCDRLL, IN_TOBSRV, IN_QATNAN, IN_PATNAN, IN_TOBSR1, IN_FLIQSR, IN_HLIQSR, IN_ULIQSR, IN_SESTSR, IN_SESTRG, IN_TOBSR, IN_SQNCB, IN_SESFAC, IN_SVLRZ, IN_FINREE, IN_HINREE, IN_FFIREE, IN_HFIREE, IN_CZNLLN);

END  ;
