--  Generar SQL 
--  Versión:                   	V7R1M0 100423 
--  Generado en:              	17/02/20 17:09:05 
--  Base de datos relacional:       	IASP 
--  Opción de estándares:          	DB2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","DC@RNSLIB" ; 
  
CREATE PROCEDURE DC@RNSLIB.SP_CONSULTA_VISCONTENEDORES_TEMP ( 
	IN IN_DESDE NUMERIC(8, 0) , 
	IN IN_HASTA NUMERIC(8, 0) , 
	IN IN_LIBRERIA VARCHAR(10) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DC@RNSLIB.SP_CONSULTA_VISCONTENEDORES_TEMP 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QGPL , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
DECLARE STRSQL VARCHAR ( 5000 ) ; 
DECLARE CU_01 CURSOR WITH RETURN FOR S1 ; 
  
SET STRSQL = 'SELECT R.NORSRN,CASE IFNULL(F.FLGETR,'''')	          	
	          	WHEN '''' THEN  D.TCMPVP	          	
	        	ELSE RTRIM(D.TCMPVP) || '' - TRANSITO''
	        	END AS TCMPVP,
 A.NBKNCN, B.CPRCN6, B.NSRCN6, 
R.TOBSOR AS TPOBKN,
B.TTMNCN, B.CTPOC2, IFNULL(C.NGSLCN,0) AS NGSLCN , IFNULL(E.FPSDSL,0) AS FPSDSL,IFNULL(E.HPSDSL,0) AS HPSDSL, IFNULL(N.FGINAL,0) AS FGINAL, IFNULL(N.HGINAL,0) AS HGINAL,
CASE 
WHEN F.FLGETR IS NULL THEN ''N''
WHEN F.FLGETR ='''' THEN ''N''
ELSE F.FLGETR
END AS FLGETR, 
CASE IFNULL(G.CCIMO1,'''')
        WHEN ''''
        THEN
                CASE IFNULL(G.CCIMO2,'''')
                WHEN ''''
                THEN
                        CASE IFNULL(G.CCIMO3,'''')
                        WHEN ''''
                        THEN ''''
                        ELSE ''IMO''
                        END
                ELSE ''IMO''
                END
        ELSE ''IMO''
    END AS IMO,
    CASE IFNULL(F.NIQBF,'''')
                WHEN ''''
                THEN ''''
                ELSE ''IQBF''
                END AS IQBF,
  CASE H.FLGPRC
  WHEN ''D'' THEN ''DOCUMENTARIO''
  WHEN ''F'' THEN ''FISICO''
  ELSE ''''
  END AS FLGPRC,
  IFNULL(E.NPRGS2,'''') AS NPRGS2,
  A.TEMBR1,
  IFNULL(C.NORDEM,0) AS NORDEM,
  CASE 
  WHEN C.NPRGI2 = '''' AND c.NPRGS2 = '''' THEN 0
  ELSE 
	  CASE A.SLGLLN 
	  WHEN ''F'' THEN
	  		CASE (SELECT count(*) FROM  ' || IN_LIBRERIA || '.RZET01 TMP WHERE TMP.NORSRN = R.NORSRN AND TMP.CPRCN3 = B.CPRCN6 AND TMP.NSRCN3 = B.NSRCN6 AND TMP.SESTRG  <> ''*'')
	  			WHEN 0 THEN IFNULL((SELECT SUM(PBLTMR)  FROM  ' || IN_LIBRERIA || '.RZET01 TMP WHERE TMP.NORSRN = R.NORSRN AND TMP.CPRCN3 = B.CPRCN6 AND TMP.NSRCN3 = B.NSRCN6 AND TMP.SESTRG  <> ''*''),0)
	  			WHEN 1 THEN (SELECT SUM(PBLTMR)  FROM  ' || IN_LIBRERIA || '.RZET01 TMP WHERE TMP.NORSRN = R.NORSRN AND TMP.CPRCN3 = B.CPRCN6 AND TMP.NSRCN3 = B.NSRCN6 AND TMP.SESTRG  <> ''*'' )  			
	  			ELSE IFNULL( (SELECT SUM(IFNULL(PBLTMR,0))  FROM  ' || IN_LIBRERIA || '.RZET01 TMP WHERE TMP.NORSRN = R.NORSRN AND TMP.CPRCN3 = B.CPRCN6 AND TMP.NSRCN3 = B.NSRCN6 AND TMP.SESTRG  <> ''*''),0) + IFNULL(C.PTRCNT,0) 
	  			END
	  WHEN ''C'' THEN
	  		CASE IFNULL(J.FUNCBS,'''')
	  			WHEN ''X'' THEN (SELECT SUM(PBLTMR)  FROM  ' || IN_LIBRERIA || '.RZET01 TMP WHERE TMP.NORSRN = R.NORSRN AND TMP.CPRCN3 = B.CPRCN6 AND TMP.NSRCN3 = B.NSRCN6 AND TMP.SESTRG  <> ''*'')  			
	  			ELSE IFNULL((SELECT SUM(IFNULL(PBLTMR,0))  FROM  ' || IN_LIBRERIA || '.RZET01 TMP WHERE TMP.NORSRN = R.NORSRN AND TMP.CPRCN3 = B.CPRCN6 AND TMP.NSRCN3 = B.NSRCN6 AND TMP.SESTRG  <> ''*''),0) + IFNULL(C.PTRCNT,0) 
	  			END
	  ELSE  0
	  END 
 END AS PESO,IFNULL(C.PTRCNT,0) AS TARA,
  CASE K.FLGOPP
WHEN ''D'' THEN ''DPW''
WHEN ''A'' THEN ''APM''
ELSE ''''
END AS FLGOPP,
 IFNULL(M.FCOFF1,0) AS FCOFF1, IFNULL(M.HCOFF1,0) AS HCOFF1
 FROM ' || IN_LIBRERIA || '.RZIT22 R
 INNER JOIN ' || IN_LIBRERIA || '.RZZT17 A ON R.NORSRN = A.NORSRN  AND A.SESTRG  <> ''*''
 INNER JOIN ' || IN_LIBRERIA || '.RZZT18 B ON R.NORSRN = B.NORSRN AND A.NBKNCN = B.NBKNCN  AND A.SESTRG  <> ''*''
 LEFT JOIN ' || IN_LIBRERIA || '.RZET02 C ON  R.NORSRN = C.NORSRN AND B.CPRCN6 = C.CPRCN4 AND B.NSRCN6 = C.NSRCN4
 LEFT JOIN ' || IN_LIBRERIA || '.RZZK08 D ON R.CVPRCN = D.CVPRCN
 LEFT JOIN ' || IN_LIBRERIA || '.RZIM23 E ON C.NGSLCN = E.NGASLD
 LEFT JOIN ' || IN_LIBRERIA || '.RZET90 F ON R.NORSRN = F.NORSRN AND A.NBKNCN = F.NBKNCN
 LEFT JOIN ' || IN_LIBRERIA || '.RZET86 G ON R.NORSRN = G.NORSRN AND A.NBKNCN = G.NBKNCN AND B.NDTBKN = G.NDTBKN
 LEFT JOIN ' || IN_LIBRERIA || '.RZET21 H ON R.NORSRN = H.NORSRN AND A.NBKNCN = H.NBKNCN AND B.CPRCN6 = H.CPRPCN AND B.NSRCN6 = H.NSRECN AND C.NGINCN = H.NGINSS
 LEFT JOIN ' || IN_LIBRERIA || '.RZTW42 J ON R.NORSRN = J.NORSRN AND A.NBKNCN = J.NBKNCN  
LEFT JOIN ' || IN_LIBRERIA || '.RZTW05 K ON R.NORSRN = K.NORSRN
LEFT JOIN ' || IN_LIBRERIA || '.RZET08 L ON R.NORSRN = L.NORSRN
LEFT JOIN ' || IN_LIBRERIA || '.RZET07 M ON L.NMRLQO = M.NMRLQO
LEFT JOIN ' || IN_LIBRERIA || '.RZIT26 N ON C.NGINCN = N.NGINSS
 WHERE CTPOOP = 2 AND R.SESTRG  <> ''*''   AND R.FPRSAT BETWEEN ' || IN_DESDE || ' AND ' || IN_HASTA || '
 ORDER BY R.NORSRN, D.TCMPVP, F.FLGETR, E.FPSDSL, B.CPRCN6, B.NSRCN6' ; 
  
  
PREPARE S1 FROM STRSQL ; 
OPEN CU_01 USING IN_DESDE , IN_HASTA ; 
  
  
END  ;
